# Enunciado disponível em: https://projecteuler.net/problem=2

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

var
  first: int = 1
  second: int = 2
  sum: int = 0

let
  limit: int = 4_000_000

while second <= limit:
  if second mod 2 == 0:
    inc sum, second
  swap first, second
  second += first
echo sum
